### ISSUE TITLE
Linux能不能进行后台运行呀？

### ISSUE THREAD

**Issue by zhang6616** [FastTunnel/SuiDao#3]
后台运行的命令或脚本是啥呀？

**Comment by SpringHgui** [comment]
linux后台运行可以用systemd
[fasttunnel.service](https://github.com/SpringHgui/FastTunnel/blob/master/fasttunnel.service)

**Comment by zhang6616** [comment]
> linux后台运行可以用systemd
> [fasttunnel.service](https://github.com/SpringHgui/FastTunnel/blob/master/fasttunnel.service)

FastTunnel.SuiDao
用systemd
fasttunnel.service可以？我怎么看得有点蒙圈呀，大神

**Comment by SpringHgui** [comment]
参考 [Linux系统如何设置后台运行&开机自启](https://github.com/SpringHgui/FastTunnel/wiki/Linux%E7%B3%BB%E7%BB%9F%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E5%90%8E%E5%8F%B0%E8%BF%90%E8%A1%8C&%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)

FastTunnel.SuiDao项目是基于FastTunnel开发免费服务，你应该使用FastTunnel自己搭建穿透服务，因为FastTunnel.SuiDao并不能直接提供服务，有部分代码尚未开源，相比较FastTunnel更加简单

**Comment by zhang6616** [comment]
> 参考 [Linux系统如何设置后台运行&开机自启](https://github.com/SpringHgui/FastTunnel/wiki/Linux%E7%B3%BB%E7%BB%9F%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E5%90%8E%E5%8F%B0%E8%BF%90%E8%A1%8C&%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)
> 
> FastTunnel.SuiDao项目是基于FastTunnel开发免费服务，你应该使用FastTunnel自己搭建穿透服务，因为FastTunnel.SuiDao并不能直接提供服务，有部分代码尚未开源，相比较FastTunnel更加简单

FastTunnel我没有公网ip能搭建穿透服务？具体代码我也还没看，我猜应该是需要公网IP吧

**Comment by SpringHgui** [comment]
没有公网ip不行的，那你直接使用 https://suidao.io
注册一下，建个隧道，下载客户端就行，不要部署服务端

**Comment by zhang6616** [comment]
> 没有公网ip不行的，那你直接使用 https://suidao.io
> 注册一下，建个隧道，下载客户端就行，不要部署服务端

嗯嗯，谢谢大神，目前就是不知道客户端怎样设置后台运行，试过shell脚本也不行

**Comment by SpringHgui** [comment]
编写一个service文件 用 systemd
