### ISSUE TITLE
win10 无法使用1.1.3版

### ISSUE THREAD

**Issue by ok1991** [FastTunnel/SuiDao#9]
SuiDao.Client.win-x64.tar.gz 

1.1.1正常使用。
1.1.3 SuiDao.Client.exe闪退。

**Comment by ioxygen** [comment]
确实存在问题，马上更新

**Comment by ioxygen** [comment]
@1136833974 已更新

**Comment by 1136833974** [comment]
> 确实存在问题，马上更新

已正常使用最新版服务，感谢更新。
